#!/usr/bin/env bash
# Reminisce — Production Install Script
# Run on the target machine: curl -fsSL <url>/install.sh | bash
# Or:  bash install.sh
set -euo pipefail

# ─── colours ──────────────────────────────────────────────────────────────────
RED='\033[0;31m'; GREEN='\033[0;32m'; YELLOW='\033[1;33m'; BLUE='\033[0;34m'; NC='\033[0m'
info()    { echo -e "${BLUE}[INFO]${NC}  $*"; }
success() { echo -e "${GREEN}[OK]${NC}    $*"; }
warn()    { echo -e "${YELLOW}[WARN]${NC}  $*"; }
error()   { echo -e "${RED}[ERROR]${NC} $*" >&2; exit 1; }

INSTALL_DIR="${INSTALL_DIR:-$(pwd)/reminisce}"
COMPOSE_URL="https://raw.githubusercontent.com/lubod/reminisce/master"

# ─── 1. Prerequisites ─────────────────────────────────────────────────────────
info "Checking prerequisites..."

command -v docker  >/dev/null 2>&1 || error "Docker not found. Install it from https://docs.docker.com/engine/install/"
command -v openssl >/dev/null 2>&1 || error "openssl not found. Install it: apt install openssl"

# Require docker compose v2 (plugin)
if ! docker compose version >/dev/null 2>&1; then
    error "Docker Compose v2 plugin not found. Install it: apt install docker-compose-plugin"
fi

DOCKER_VERSION=$(docker --version | grep -oP '\d+\.\d+' | head -1)
info "Docker $DOCKER_VERSION — OK"
success "Prerequisites satisfied"

# ─── 2. Install directory ─────────────────────────────────────────────────────
info "Setting up install directory: $INSTALL_DIR"
mkdir -p "$INSTALL_DIR"
cd "$INSTALL_DIR"

# ─── 3. Download docker-compose.yml and db/init.sql ──────────────────────────
info "Downloading docker-compose.yml..."
if command -v curl >/dev/null 2>&1; then
    curl -fsSL "$COMPOSE_URL/docker-compose.yml" -o docker-compose.yml
elif command -v wget >/dev/null 2>&1; then
    wget -qO docker-compose.yml "$COMPOSE_URL/docker-compose.yml"
else
    error "Neither curl nor wget found"
fi

info "Downloading db/init.sql..."
mkdir -p db
if command -v curl >/dev/null 2>&1; then
    curl -fsSL "$COMPOSE_URL/db/init.sql" -o db/init.sql
else
    wget -qO db/init.sql "$COMPOSE_URL/db/init.sql"
fi
success "Downloaded compose file and schema"

# ─── 3b. Patch docker-compose.yml based on hardware ──────────────────────────
if [ -d /dev/dri ]; then
    info "AMD GPU detected (/dev/dri) — enabling hardware acceleration for AI server"
    sed -i 's|#GPU#||g' docker-compose.yml
    success "GPU acceleration enabled in docker-compose.yml"
else
    info "No GPU detected — AI server will run in CPU mode (slower but functional)"
    sed -i '/#GPU#/d' docker-compose.yml
fi

# ─── 4. Create data directories ───────────────────────────────────────────────
info "Creating data directories..."
mkdir -p uploaded_images uploaded_videos data/p2p
success "Directories created"

# ─── 5. Generate .env ─────────────────────────────────────────────────────────
ENV_IS_NEW=false
if [ -f .env ]; then
    warn ".env already exists — skipping (delete it to regenerate)"
else
    info "Generating .env..."
    DB_PASS=$(openssl rand -hex 24)   # 48 hex chars, 192-bit entropy
    cat > .env <<EOF
POSTGRES_USER=postgres
POSTGRES_PASSWORD=${DB_PASS}
EOF
    chmod 600 .env
    ENV_IS_NEW=true
    success ".env created (password auto-generated, permissions: 600)"
fi

# Load env so we can embed the password in config.yaml
# shellcheck disable=SC1091
source .env
DB_PASS="${POSTGRES_PASSWORD}"

# ─── 6. Generate config.yaml ──────────────────────────────────────────────────
if [ -f config.yaml ]; then
    warn "config.yaml already exists — skipping (delete it to regenerate)"
else
    info "Generating config.yaml..."
    # base64url (no +/= chars) — safe in YAML, URLs, and HTTP headers
    JWT_SECRET=$(openssl rand -base64 48 | tr '+/' '-_' | tr -d '=\n')
    cat > config.yaml <<EOF
# Reminisce server config — generated by install.sh
# Edit this file to customise your setup, then: docker compose restart reminisce

database_url: "postgres://postgres:${DB_PASS}@postgres:5432/reminisce_db"
geotagging_database_url: "postgres://postgres:${DB_PASS}@geotagging-db:5432/geotagging_db"

# JWT signing secret — keep this private and consistent across restarts
api_secret_key: "${JWT_SECRET}"

# Media storage (Docker bind mounts)
images_dir: "/app/uploaded_images"
videos_dir: "/app/uploaded_videos"

# P2P networking
p2p_data_dir: "/app/data/p2p"
p2p_discovery_port: 5050
# Coordinator for cross-network peer discovery and relay
p2p_coordinator_addr: "dnet.openreminisce.org:5055"
# Namespace isolates this instance's storage nodes from other environments on the shared coordinator
p2p_namespace: "production"
# Reverse tunnel — lets Android reach this server via the VPS
p2p_tunnel_local_port: 8080
p2p_tunnel_public_url: "https://dnet.openreminisce.org:8443"

# AI services (internal Docker network — do not change unless you move ai-server)
embedding_service_url: "http://ai-server:8081"
face_service_url: "http://ai-server:8081"

# Geocoding
enable_local_geocoding: true
enable_external_geocoding_fallback: true
EOF
    chmod 600 config.yaml
    success "config.yaml created (permissions: 600)"
fi

# ─── 6b. Remove stale DB volumes if .env was newly generated ─────────────────
# If .env is new but old volumes exist (from a failed previous install), the
# DB was initialized with a different password — remove to avoid auth failures.
if [ "$ENV_IS_NEW" = "true" ]; then
    for vol in reminisce_postgres_data reminisce_geotagging_data; do
        if docker volume ls --format '{{.Name}}' | grep -q "^${vol}$"; then
            warn "Removing stale volume '$vol' (new password generated — volume had old credentials)"
            docker volume rm "$vol" 2>/dev/null || true
        fi
    done
fi

# ─── 7. Pull images ───────────────────────────────────────────────────────────
info "Pulling Docker images (this may take a while on first run)..."
docker compose pull
success "Images pulled"

# ─── 8. Start stack ───────────────────────────────────────────────────────────
info "Starting Reminisce..."
docker compose up -d

# ─── 8b. Set geotagging DB password ──────────────────────────────────────────
# The geodb image ships with a pre-loaded database where the postgres user has
# no password. POSTGRES_PASSWORD env var is ignored (initdb is skipped).
# We set it here via local socket which uses trust auth.
info "Configuring geotagging database credentials..."
GEODB_RETRIES=20
for i in $(seq 1 $GEODB_RETRIES); do
    if docker exec reminisce-geotagging psql -U postgres -c "ALTER USER postgres WITH PASSWORD '$DB_PASS';" 2>/dev/null; then
        success "Geotagging database password configured"
        break
    fi
    if [ "$i" = "$GEODB_RETRIES" ]; then
        warn "Could not set geotagging DB password after ${GEODB_RETRIES} attempts — check logs"
    fi
    sleep 3
done

# ─── 9. Wait for health ───────────────────────────────────────────────────────
info "Waiting for services to become healthy..."
TIMEOUT=180
ELAPSED=0

# Check whether docker compose ps can produce parseable output
_parse_health() {
    docker compose ps --format json 2>/dev/null | python3 -c "
import sys, json
lines = sys.stdin.read().strip().split('\n')
services = [json.loads(l) for l in lines if l.strip()]
unhealthy = [s['Service'] for s in services if s.get('Health','') not in ('healthy','')]
starting  = [s['Service'] for s in services if s.get('Health','') == 'starting']
print(len(unhealthy), len(starting))
" 2>/dev/null
}

if ! command -v python3 >/dev/null 2>&1; then
    warn "python3 not found — skipping health wait (check manually with: docker compose ps)"
else
    while [ $ELAPSED -lt $TIMEOUT ]; do
        STATUS=$(_parse_health || echo "ERR")
        if [ "$STATUS" = "ERR" ]; then
            warn "Could not parse health status — check manually: docker compose ps"
            break
        fi
        UNHEALTHY=$(echo "$STATUS" | awk '{print $1}')
        STARTING=$(echo "$STATUS"  | awk '{print $2}')

        if [ "$UNHEALTHY" = "0" ]; then
            break
        fi
        if [ "$STARTING" = "0" ] && [ "$UNHEALTHY" != "0" ]; then
            docker compose ps
            error "One or more services failed to start. Check logs: docker compose logs"
        fi
        sleep 5
        ELAPSED=$((ELAPSED + 5))
        echo -ne "  ${ELAPSED}s / ${TIMEOUT}s ...\r"
    done
    echo ""
fi

# ─── 10. Done ─────────────────────────────────────────────────────────────────
echo ""
echo -e "${GREEN}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo -e "${GREEN}  Reminisce is running!${NC}"
echo -e "${GREEN}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo ""
HOST_IP=$(hostname -I | tr ' ' '\n' | grep -v '^127\.' | grep -v '^172\.' | grep -v '^::1' | head -1)
HOST_IP="${HOST_IP:-$(hostname -I | awk '{print $1}')}"
echo -e "  UI (HTTPS):  ${BLUE}https://${HOST_IP}:28443${NC}"
echo -e "  UI (HTTP):   ${BLUE}http://${HOST_IP}:28080${NC}"
echo ""
echo -e "  On first visit, go through the setup wizard to create your admin account."
echo ""
echo -e "  Useful commands:"
echo -e "    docker compose --project-directory $INSTALL_DIR ps          # service status"
echo -e "    docker compose --project-directory $INSTALL_DIR logs -f     # live logs"
echo -e "    docker compose --project-directory $INSTALL_DIR pull && docker compose --project-directory $INSTALL_DIR up -d  # update"
echo ""
echo -e "  Config: ${INSTALL_DIR}/config.yaml"
echo -e "  Data:   ${INSTALL_DIR}/uploaded_images  |  uploaded_videos  |  data/p2p"
echo ""
