# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import ai_service_pb2 as ai__service__pb2

GRPC_GENERATED_VERSION = '1.83.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in ai_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class AIServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.EmbedImage = channel.unary_unary(
                '/ai_service.AIService/EmbedImage',
                request_serializer=ai__service__pb2.EmbedImageRequest.SerializeToString,
                response_deserializer=ai__service__pb2.EmbedImageResponse.FromString,
                _registered_method=True)
        self.EmbedText = channel.unary_unary(
                '/ai_service.AIService/EmbedText',
                request_serializer=ai__service__pb2.EmbedTextRequest.SerializeToString,
                response_deserializer=ai__service__pb2.EmbedTextResponse.FromString,
                _registered_method=True)
        self.DescribeImage = channel.unary_unary(
                '/ai_service.AIService/DescribeImage',
                request_serializer=ai__service__pb2.DescribeImageRequest.SerializeToString,
                response_deserializer=ai__service__pb2.DescribeImageResponse.FromString,
                _registered_method=True)
        self.DetectFaces = channel.unary_unary(
                '/ai_service.AIService/DetectFaces',
                request_serializer=ai__service__pb2.DetectFacesRequest.SerializeToString,
                response_deserializer=ai__service__pb2.DetectFacesResponse.FromString,
                _registered_method=True)
        self.HealthCheck = channel.unary_unary(
                '/ai_service.AIService/HealthCheck',
                request_serializer=ai__service__pb2.HealthCheckRequest.SerializeToString,
                response_deserializer=ai__service__pb2.HealthCheckResponse.FromString,
                _registered_method=True)


class AIServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def EmbedImage(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def EmbedText(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DescribeImage(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DetectFaces(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def HealthCheck(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AIServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'EmbedImage': grpc.unary_unary_rpc_method_handler(
                    servicer.EmbedImage,
                    request_deserializer=ai__service__pb2.EmbedImageRequest.FromString,
                    response_serializer=ai__service__pb2.EmbedImageResponse.SerializeToString,
            ),
            'EmbedText': grpc.unary_unary_rpc_method_handler(
                    servicer.EmbedText,
                    request_deserializer=ai__service__pb2.EmbedTextRequest.FromString,
                    response_serializer=ai__service__pb2.EmbedTextResponse.SerializeToString,
            ),
            'DescribeImage': grpc.unary_unary_rpc_method_handler(
                    servicer.DescribeImage,
                    request_deserializer=ai__service__pb2.DescribeImageRequest.FromString,
                    response_serializer=ai__service__pb2.DescribeImageResponse.SerializeToString,
            ),
            'DetectFaces': grpc.unary_unary_rpc_method_handler(
                    servicer.DetectFaces,
                    request_deserializer=ai__service__pb2.DetectFacesRequest.FromString,
                    response_serializer=ai__service__pb2.DetectFacesResponse.SerializeToString,
            ),
            'HealthCheck': grpc.unary_unary_rpc_method_handler(
                    servicer.HealthCheck,
                    request_deserializer=ai__service__pb2.HealthCheckRequest.FromString,
                    response_serializer=ai__service__pb2.HealthCheckResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ai_service.AIService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('ai_service.AIService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AIService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def EmbedImage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ai_service.AIService/EmbedImage',
            ai__service__pb2.EmbedImageRequest.SerializeToString,
            ai__service__pb2.EmbedImageResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def EmbedText(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ai_service.AIService/EmbedText',
            ai__service__pb2.EmbedTextRequest.SerializeToString,
            ai__service__pb2.EmbedTextResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DescribeImage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ai_service.AIService/DescribeImage',
            ai__service__pb2.DescribeImageRequest.SerializeToString,
            ai__service__pb2.DescribeImageResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DetectFaces(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ai_service.AIService/DetectFaces',
            ai__service__pb2.DetectFacesRequest.SerializeToString,
            ai__service__pb2.DetectFacesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def HealthCheck(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ai_service.AIService/HealthCheck',
            ai__service__pb2.HealthCheckRequest.SerializeToString,
            ai__service__pb2.HealthCheckResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
